CREATE TABLE ZOOLOGICOS (
id_zoo SERIAL PRIMARY KEY,
nombre VARCHAR(50) NOT NULL,
ciudad VARCHAR(50) NOT NULL,
paiz VARCHAR(50) NOT NULL,
tamaño VARCHAR(20) NOT NULL,
presupuesto VARCHAR(20) NOT NULL
);

CREATE TABLE ESPECIES (
id_especie SERIAL PRIMARY KEY,
nombre_vulgar VARCHAR(50) NOT NULL,
nombre_cientifico VARCHAR(50) NOT NULL,
familia VARCHAR(50) NOT NULL,
en_peligro VARCHAR(20) NOT NULL
);

CREATE TABLE ANIMALES (
id_animal SERIAL PRIMARY KEY,
sexo VARCHAR(10) NOT NULL,
anio_nacimiento VARCHAR(50) NOT NULL,
paiz_origen VARCHAR(50) NOT NULL,
contnente VARCHAR(20) NOT NULL,
FOREIGN KEY (id_zoo) REFERENCES
ZOOLOGICOS(id_zoo),
FOREIGN KEY (id_especie) REFERENCES
ESPECIES(id_especie)
);
